// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: protobuf/market-services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MarketService_GetMarketDashboard_FullMethodName      = "/dapplink.xyz.MarketService/GetMarketDashboard"
	MarketService_GetAssetDashboard_FullMethodName       = "/dapplink.xyz.MarketService/GetAssetDashboard"
	MarketService_GetMarketInsights_FullMethodName       = "/dapplink.xyz.MarketService/GetMarketInsights"
	MarketService_GetKlines_FullMethodName               = "/dapplink.xyz.MarketService/GetKlines"
	MarketService_GetSystemOverview_FullMethodName       = "/dapplink.xyz.MarketService/GetSystemOverview"
	MarketService_GetSupportAssets_FullMethodName        = "/dapplink.xyz.MarketService/GetSupportAssets"
	MarketService_GetSymbols_FullMethodName              = "/dapplink.xyz.MarketService/GetSymbols"
	MarketService_GetExchanges_FullMethodName            = "/dapplink.xyz.MarketService/GetExchanges"
	MarketService_GetFiatRates_FullMethodName            = "/dapplink.xyz.MarketService/GetFiatRates"
	MarketService_GetTopMovers_FullMethodName            = "/dapplink.xyz.MarketService/GetTopMovers"
	MarketService_GetMarketSparklines_FullMethodName     = "/dapplink.xyz.MarketService/GetMarketSparklines"
	MarketService_GetMarketOverview_FullMethodName       = "/dapplink.xyz.MarketService/GetMarketOverview"
	MarketService_GetAssetDashboardV2_FullMethodName     = "/dapplink.xyz.MarketService/GetAssetDashboardV2"
	MarketService_GetAssetMarkets_FullMethodName         = "/dapplink.xyz.MarketService/GetAssetMarkets"
	MarketService_GetAssetVenues_FullMethodName          = "/dapplink.xyz.MarketService/GetAssetVenues"
	MarketService_GetProviderCatalogAudit_FullMethodName = "/dapplink.xyz.MarketService/GetProviderCatalogAudit"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	// 行情大盘列表（分页，可选按交易所过滤）—— 对应 POST /api/v1/get_market_dashboard
	GetMarketDashboard(ctx context.Context, in *MarketDashboardRequest, opts ...grpc.CallOption) (*MarketDashboardResponse, error)
	// 资产聚合大盘 —— 对应 POST /api/v1/get_asset_dashboard
	GetAssetDashboard(ctx context.Context, in *AssetDashboardRequest, opts ...grpc.CallOption) (*AssetDashboardResponse, error)
	// 实时市场宽度与跨 venue 对比 —— 对应 POST /api/v1/get_market_insights
	GetMarketInsights(ctx context.Context, in *MarketInsightsRequest, opts ...grpc.CallOption) (*MarketInsightsResponse, error)
	// K 线 —— 对应 POST /api/v1/get_klines
	GetKlines(ctx context.Context, in *KlinesRequest, opts ...grpc.CallOption) (*KlinesResponse, error)
	// 系统总览 —— 对应 POST /api/v1/get_system_overview
	GetSystemOverview(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*SystemOverviewResponse, error)
	// 支持的资产列表 —— 对应 POST /api/v1/get_support_assets
	GetSupportAssets(ctx context.Context, in *SupportAssetRequest, opts ...grpc.CallOption) (*SupportAssetResponse, error)
	// 交易对列表 —— 对应 POST /api/v1/get_symbols
	GetSymbols(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*SymbolResponse, error)
	// 交易所列表 —— 对应 POST /api/v1/get_exchanges
	GetExchanges(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
	// 法币汇率 —— 对应 POST /api/v1/get_fiat_rates
	GetFiatRates(ctx context.Context, in *FiatRatesRequest, opts ...grpc.CallOption) (*FiatRatesResponse, error)
	// 24h 涨幅榜 / 跌幅榜 —— 对应 POST /api/v1/get_top_movers
	GetTopMovers(ctx context.Context, in *TopMoversRequest, opts ...grpc.CallOption) (*TopMoversResponse, error)
	// Markets 当前页的批量迷你走势 —— 对应 POST /api/v1/get_market_sparklines
	GetMarketSparklines(ctx context.Context, in *MarketSparklinesRequest, opts ...grpc.CallOption) (*MarketSparklinesResponse, error)
	// 多交易所综合现货首页概览 —— 对应 POST /api/v2/get_market_overview
	GetMarketOverview(ctx context.Context, in *MarketOverviewRequest, opts ...grpc.CallOption) (*MarketOverviewResponse, error)
	// 资产综合价排行榜 —— 对应 POST /api/v2/get_asset_dashboard
	GetAssetDashboardV2(ctx context.Context, in *AssetDashboardV2Request, opts ...grpc.CallOption) (*AssetDashboardV2Response, error)
	// 资产的具体 Spot / Perp 市场 —— 对应 POST /api/v2/get_asset_markets
	GetAssetMarkets(ctx context.Context, in *AssetMarketsRequest, opts ...grpc.CallOption) (*AssetMarketsResponse, error)
	// 资产的 CEX / Perp / DEX 路线 —— 对应 POST /api/v2/get_asset_venues
	GetAssetVenues(ctx context.Context, in *AssetMarketsRequest, opts ...grpc.CallOption) (*AssetMarketsResponse, error)
	// provider 目录审计 —— 对应 POST /api/v2/get_provider_catalog_audit
	GetProviderCatalogAudit(ctx context.Context, in *ProviderCatalogAuditRequest, opts ...grpc.CallOption) (*ProviderCatalogAuditResponse, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) GetMarketDashboard(ctx context.Context, in *MarketDashboardRequest, opts ...grpc.CallOption) (*MarketDashboardResponse, error) {
	out := new(MarketDashboardResponse)
	err := c.cc.Invoke(ctx, MarketService_GetMarketDashboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetAssetDashboard(ctx context.Context, in *AssetDashboardRequest, opts ...grpc.CallOption) (*AssetDashboardResponse, error) {
	out := new(AssetDashboardResponse)
	err := c.cc.Invoke(ctx, MarketService_GetAssetDashboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetMarketInsights(ctx context.Context, in *MarketInsightsRequest, opts ...grpc.CallOption) (*MarketInsightsResponse, error) {
	out := new(MarketInsightsResponse)
	err := c.cc.Invoke(ctx, MarketService_GetMarketInsights_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetKlines(ctx context.Context, in *KlinesRequest, opts ...grpc.CallOption) (*KlinesResponse, error) {
	out := new(KlinesResponse)
	err := c.cc.Invoke(ctx, MarketService_GetKlines_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetSystemOverview(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*SystemOverviewResponse, error) {
	out := new(SystemOverviewResponse)
	err := c.cc.Invoke(ctx, MarketService_GetSystemOverview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetSupportAssets(ctx context.Context, in *SupportAssetRequest, opts ...grpc.CallOption) (*SupportAssetResponse, error) {
	out := new(SupportAssetResponse)
	err := c.cc.Invoke(ctx, MarketService_GetSupportAssets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetSymbols(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*SymbolResponse, error) {
	out := new(SymbolResponse)
	err := c.cc.Invoke(ctx, MarketService_GetSymbols_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetExchanges(ctx context.Context, in *CommonRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, MarketService_GetExchanges_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetFiatRates(ctx context.Context, in *FiatRatesRequest, opts ...grpc.CallOption) (*FiatRatesResponse, error) {
	out := new(FiatRatesResponse)
	err := c.cc.Invoke(ctx, MarketService_GetFiatRates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetTopMovers(ctx context.Context, in *TopMoversRequest, opts ...grpc.CallOption) (*TopMoversResponse, error) {
	out := new(TopMoversResponse)
	err := c.cc.Invoke(ctx, MarketService_GetTopMovers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetMarketSparklines(ctx context.Context, in *MarketSparklinesRequest, opts ...grpc.CallOption) (*MarketSparklinesResponse, error) {
	out := new(MarketSparklinesResponse)
	err := c.cc.Invoke(ctx, MarketService_GetMarketSparklines_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetMarketOverview(ctx context.Context, in *MarketOverviewRequest, opts ...grpc.CallOption) (*MarketOverviewResponse, error) {
	out := new(MarketOverviewResponse)
	err := c.cc.Invoke(ctx, MarketService_GetMarketOverview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetAssetDashboardV2(ctx context.Context, in *AssetDashboardV2Request, opts ...grpc.CallOption) (*AssetDashboardV2Response, error) {
	out := new(AssetDashboardV2Response)
	err := c.cc.Invoke(ctx, MarketService_GetAssetDashboardV2_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetAssetMarkets(ctx context.Context, in *AssetMarketsRequest, opts ...grpc.CallOption) (*AssetMarketsResponse, error) {
	out := new(AssetMarketsResponse)
	err := c.cc.Invoke(ctx, MarketService_GetAssetMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetAssetVenues(ctx context.Context, in *AssetMarketsRequest, opts ...grpc.CallOption) (*AssetMarketsResponse, error) {
	out := new(AssetMarketsResponse)
	err := c.cc.Invoke(ctx, MarketService_GetAssetVenues_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketServiceClient) GetProviderCatalogAudit(ctx context.Context, in *ProviderCatalogAuditRequest, opts ...grpc.CallOption) (*ProviderCatalogAuditResponse, error) {
	out := new(ProviderCatalogAuditResponse)
	err := c.cc.Invoke(ctx, MarketService_GetProviderCatalogAudit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility
type MarketServiceServer interface {
	// 行情大盘列表（分页，可选按交易所过滤）—— 对应 POST /api/v1/get_market_dashboard
	GetMarketDashboard(context.Context, *MarketDashboardRequest) (*MarketDashboardResponse, error)
	// 资产聚合大盘 —— 对应 POST /api/v1/get_asset_dashboard
	GetAssetDashboard(context.Context, *AssetDashboardRequest) (*AssetDashboardResponse, error)
	// 实时市场宽度与跨 venue 对比 —— 对应 POST /api/v1/get_market_insights
	GetMarketInsights(context.Context, *MarketInsightsRequest) (*MarketInsightsResponse, error)
	// K 线 —— 对应 POST /api/v1/get_klines
	GetKlines(context.Context, *KlinesRequest) (*KlinesResponse, error)
	// 系统总览 —— 对应 POST /api/v1/get_system_overview
	GetSystemOverview(context.Context, *CommonRequest) (*SystemOverviewResponse, error)
	// 支持的资产列表 —— 对应 POST /api/v1/get_support_assets
	GetSupportAssets(context.Context, *SupportAssetRequest) (*SupportAssetResponse, error)
	// 交易对列表 —— 对应 POST /api/v1/get_symbols
	GetSymbols(context.Context, *CommonRequest) (*SymbolResponse, error)
	// 交易所列表 —— 对应 POST /api/v1/get_exchanges
	GetExchanges(context.Context, *CommonRequest) (*ExchangeResponse, error)
	// 法币汇率 —— 对应 POST /api/v1/get_fiat_rates
	GetFiatRates(context.Context, *FiatRatesRequest) (*FiatRatesResponse, error)
	// 24h 涨幅榜 / 跌幅榜 —— 对应 POST /api/v1/get_top_movers
	GetTopMovers(context.Context, *TopMoversRequest) (*TopMoversResponse, error)
	// Markets 当前页的批量迷你走势 —— 对应 POST /api/v1/get_market_sparklines
	GetMarketSparklines(context.Context, *MarketSparklinesRequest) (*MarketSparklinesResponse, error)
	// 多交易所综合现货首页概览 —— 对应 POST /api/v2/get_market_overview
	GetMarketOverview(context.Context, *MarketOverviewRequest) (*MarketOverviewResponse, error)
	// 资产综合价排行榜 —— 对应 POST /api/v2/get_asset_dashboard
	GetAssetDashboardV2(context.Context, *AssetDashboardV2Request) (*AssetDashboardV2Response, error)
	// 资产的具体 Spot / Perp 市场 —— 对应 POST /api/v2/get_asset_markets
	GetAssetMarkets(context.Context, *AssetMarketsRequest) (*AssetMarketsResponse, error)
	// 资产的 CEX / Perp / DEX 路线 —— 对应 POST /api/v2/get_asset_venues
	GetAssetVenues(context.Context, *AssetMarketsRequest) (*AssetMarketsResponse, error)
	// provider 目录审计 —— 对应 POST /api/v2/get_provider_catalog_audit
	GetProviderCatalogAudit(context.Context, *ProviderCatalogAuditRequest) (*ProviderCatalogAuditResponse, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketServiceServer struct {
}

func (UnimplementedMarketServiceServer) GetMarketDashboard(context.Context, *MarketDashboardRequest) (*MarketDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketDashboard not implemented")
}
func (UnimplementedMarketServiceServer) GetAssetDashboard(context.Context, *AssetDashboardRequest) (*AssetDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetDashboard not implemented")
}
func (UnimplementedMarketServiceServer) GetMarketInsights(context.Context, *MarketInsightsRequest) (*MarketInsightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketInsights not implemented")
}
func (UnimplementedMarketServiceServer) GetKlines(context.Context, *KlinesRequest) (*KlinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKlines not implemented")
}
func (UnimplementedMarketServiceServer) GetSystemOverview(context.Context, *CommonRequest) (*SystemOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemOverview not implemented")
}
func (UnimplementedMarketServiceServer) GetSupportAssets(context.Context, *SupportAssetRequest) (*SupportAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportAssets not implemented")
}
func (UnimplementedMarketServiceServer) GetSymbols(context.Context, *CommonRequest) (*SymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (UnimplementedMarketServiceServer) GetExchanges(context.Context, *CommonRequest) (*ExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchanges not implemented")
}
func (UnimplementedMarketServiceServer) GetFiatRates(context.Context, *FiatRatesRequest) (*FiatRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiatRates not implemented")
}
func (UnimplementedMarketServiceServer) GetTopMovers(context.Context, *TopMoversRequest) (*TopMoversResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopMovers not implemented")
}
func (UnimplementedMarketServiceServer) GetMarketSparklines(context.Context, *MarketSparklinesRequest) (*MarketSparklinesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketSparklines not implemented")
}
func (UnimplementedMarketServiceServer) GetMarketOverview(context.Context, *MarketOverviewRequest) (*MarketOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketOverview not implemented")
}
func (UnimplementedMarketServiceServer) GetAssetDashboardV2(context.Context, *AssetDashboardV2Request) (*AssetDashboardV2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetDashboardV2 not implemented")
}
func (UnimplementedMarketServiceServer) GetAssetMarkets(context.Context, *AssetMarketsRequest) (*AssetMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetMarkets not implemented")
}
func (UnimplementedMarketServiceServer) GetAssetVenues(context.Context, *AssetMarketsRequest) (*AssetMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetVenues not implemented")
}
func (UnimplementedMarketServiceServer) GetProviderCatalogAudit(context.Context, *ProviderCatalogAuditRequest) (*ProviderCatalogAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderCatalogAudit not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_GetMarketDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketDashboard(ctx, req.(*MarketDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetAssetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetAssetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetAssetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetAssetDashboard(ctx, req.(*AssetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetMarketInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketInsights(ctx, req.(*MarketInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetKlines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KlinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetKlines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetKlines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetKlines(ctx, req.(*KlinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetSystemOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetSystemOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetSystemOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetSystemOverview(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetSupportAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetSupportAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetSupportAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetSupportAssets(ctx, req.(*SupportAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetSymbols(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetExchanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetExchanges(ctx, req.(*CommonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetFiatRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FiatRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetFiatRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetFiatRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetFiatRates(ctx, req.(*FiatRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetTopMovers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopMoversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetTopMovers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetTopMovers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetTopMovers(ctx, req.(*TopMoversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetMarketSparklines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketSparklinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketSparklines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketSparklines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketSparklines(ctx, req.(*MarketSparklinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetMarketOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetMarketOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetMarketOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetMarketOverview(ctx, req.(*MarketOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetAssetDashboardV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetDashboardV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetAssetDashboardV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetAssetDashboardV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetAssetDashboardV2(ctx, req.(*AssetDashboardV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetAssetMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetAssetMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetAssetMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetAssetMarkets(ctx, req.(*AssetMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetAssetVenues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetAssetVenues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetAssetVenues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetAssetVenues(ctx, req.(*AssetMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketService_GetProviderCatalogAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderCatalogAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetProviderCatalogAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetProviderCatalogAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetProviderCatalogAudit(ctx, req.(*ProviderCatalogAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapplink.xyz.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketDashboard",
			Handler:    _MarketService_GetMarketDashboard_Handler,
		},
		{
			MethodName: "GetAssetDashboard",
			Handler:    _MarketService_GetAssetDashboard_Handler,
		},
		{
			MethodName: "GetMarketInsights",
			Handler:    _MarketService_GetMarketInsights_Handler,
		},
		{
			MethodName: "GetKlines",
			Handler:    _MarketService_GetKlines_Handler,
		},
		{
			MethodName: "GetSystemOverview",
			Handler:    _MarketService_GetSystemOverview_Handler,
		},
		{
			MethodName: "GetSupportAssets",
			Handler:    _MarketService_GetSupportAssets_Handler,
		},
		{
			MethodName: "GetSymbols",
			Handler:    _MarketService_GetSymbols_Handler,
		},
		{
			MethodName: "GetExchanges",
			Handler:    _MarketService_GetExchanges_Handler,
		},
		{
			MethodName: "GetFiatRates",
			Handler:    _MarketService_GetFiatRates_Handler,
		},
		{
			MethodName: "GetTopMovers",
			Handler:    _MarketService_GetTopMovers_Handler,
		},
		{
			MethodName: "GetMarketSparklines",
			Handler:    _MarketService_GetMarketSparklines_Handler,
		},
		{
			MethodName: "GetMarketOverview",
			Handler:    _MarketService_GetMarketOverview_Handler,
		},
		{
			MethodName: "GetAssetDashboardV2",
			Handler:    _MarketService_GetAssetDashboardV2_Handler,
		},
		{
			MethodName: "GetAssetMarkets",
			Handler:    _MarketService_GetAssetMarkets_Handler,
		},
		{
			MethodName: "GetAssetVenues",
			Handler:    _MarketService_GetAssetVenues_Handler,
		},
		{
			MethodName: "GetProviderCatalogAudit",
			Handler:    _MarketService_GetProviderCatalogAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/market-services.proto",
}
