// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: trading.proto

package tradingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_trading_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_trading_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{1}
}

type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_trading_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_trading_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{2}
}

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Side          Side                   `protobuf:"varint,4,opt,name=side,proto3,enum=s78.trading.v1.Side" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=s78.trading.v1.OrderType" json:"type,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=s78.trading.v1.TimeInForce" json:"time_in_force,omitempty"`
	PostOnly      bool                   `protobuf:"varint,7,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	Price         string                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuoteBudget   string                 `protobuf:"bytes,10,opt,name=quote_budget,json=quoteBudget,proto3" json:"quote_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *SubmitOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SubmitOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *SubmitOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuoteBudget() string {
	if x != nil {
		return x.QuoteBudget
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CancelOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CancelOrderRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OpenOnly      bool                   `protobuf:"varint,3,opt,name=open_only,json=openOnly,proto3" json:"open_only,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ListOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListOrdersRequest) GetOpenOnly() bool {
	if x != nil {
		return x.OpenOnly
	}
	return false
}

func (x *ListOrdersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{5}
}

func (x *ListTradesRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ListTradesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTradesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_trading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{6}
}

func (x *ListTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_trading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalancesRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetBalancesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_trading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Levels        uint32                 `protobuf:"varint,2,opt,name=levels,proto3" json:"levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_trading_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderBookRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *GetOrderBookRequest) GetLevels() uint32 {
	if x != nil {
		return x.Levels
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_trading_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatusRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type GetRecoveryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecoveryStatusRequest) Reset() {
	*x = GetRecoveryStatusRequest{}
	mi := &file_trading_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecoveryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecoveryStatusRequest) ProtoMessage() {}

func (x *GetRecoveryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecoveryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRecoveryStatusRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecoveryStatusRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type RecoveryBinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	EpochId         string                 `protobuf:"bytes,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	RuntimeSequence string                 `protobuf:"bytes,4,opt,name=runtime_sequence,json=runtimeSequence,proto3" json:"runtime_sequence,omitempty"`
	StateHash       string                 `protobuf:"bytes,5,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	Provenance      *RecoveryProvenance    `protobuf:"bytes,6,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecoveryBinding) Reset() {
	*x = RecoveryBinding{}
	mi := &file_trading_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryBinding) ProtoMessage() {}

func (x *RecoveryBinding) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryBinding.ProtoReflect.Descriptor instead.
func (*RecoveryBinding) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{12}
}

func (x *RecoveryBinding) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RecoveryBinding) GetEpochId() string {
	if x != nil {
		return x.EpochId
	}
	return ""
}

func (x *RecoveryBinding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RecoveryBinding) GetRuntimeSequence() string {
	if x != nil {
		return x.RuntimeSequence
	}
	return ""
}

func (x *RecoveryBinding) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *RecoveryBinding) GetProvenance() *RecoveryProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type RecoveryProvenance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductionOrigin string                 `protobuf:"bytes,1,opt,name=production_origin,json=productionOrigin,proto3" json:"production_origin,omitempty"`
	DeploymentId     string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	ReleaseCommit    string                 `protobuf:"bytes,3,opt,name=release_commit,json=releaseCommit,proto3" json:"release_commit,omitempty"`
	SourceDigest     string                 `protobuf:"bytes,4,opt,name=source_digest,json=sourceDigest,proto3" json:"source_digest,omitempty"`
	DeploymentUrl    string                 `protobuf:"bytes,5,opt,name=deployment_url,json=deploymentUrl,proto3" json:"deployment_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecoveryProvenance) Reset() {
	*x = RecoveryProvenance{}
	mi := &file_trading_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryProvenance) ProtoMessage() {}

func (x *RecoveryProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryProvenance.ProtoReflect.Descriptor instead.
func (*RecoveryProvenance) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{13}
}

func (x *RecoveryProvenance) GetProductionOrigin() string {
	if x != nil {
		return x.ProductionOrigin
	}
	return ""
}

func (x *RecoveryProvenance) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *RecoveryProvenance) GetReleaseCommit() string {
	if x != nil {
		return x.ReleaseCommit
	}
	return ""
}

func (x *RecoveryProvenance) GetSourceDigest() string {
	if x != nil {
		return x.SourceDigest
	}
	return ""
}

func (x *RecoveryProvenance) GetDeploymentUrl() string {
	if x != nil {
		return x.DeploymentUrl
	}
	return ""
}

type RecoveryTransportEvidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SampleCount    uint32                 `protobuf:"varint,1,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	FirstSampleAt  string                 `protobuf:"bytes,2,opt,name=first_sample_at,json=firstSampleAt,proto3" json:"first_sample_at,omitempty"`
	LastSampleAt   string                 `protobuf:"bytes,3,opt,name=last_sample_at,json=lastSampleAt,proto3" json:"last_sample_at,omitempty"`
	MaximumGapMs   string                 `protobuf:"bytes,4,opt,name=maximum_gap_ms,json=maximumGapMs,proto3" json:"maximum_gap_ms,omitempty"`
	EvidenceSha256 string                 `protobuf:"bytes,5,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	Provenance     *RecoveryProvenance    `protobuf:"bytes,6,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecoveryTransportEvidence) Reset() {
	*x = RecoveryTransportEvidence{}
	mi := &file_trading_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryTransportEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryTransportEvidence) ProtoMessage() {}

func (x *RecoveryTransportEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryTransportEvidence.ProtoReflect.Descriptor instead.
func (*RecoveryTransportEvidence) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{14}
}

func (x *RecoveryTransportEvidence) GetSampleCount() uint32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *RecoveryTransportEvidence) GetFirstSampleAt() string {
	if x != nil {
		return x.FirstSampleAt
	}
	return ""
}

func (x *RecoveryTransportEvidence) GetLastSampleAt() string {
	if x != nil {
		return x.LastSampleAt
	}
	return ""
}

func (x *RecoveryTransportEvidence) GetMaximumGapMs() string {
	if x != nil {
		return x.MaximumGapMs
	}
	return ""
}

func (x *RecoveryTransportEvidence) GetEvidenceSha256() string {
	if x != nil {
		return x.EvidenceSha256
	}
	return ""
}

func (x *RecoveryTransportEvidence) GetProvenance() *RecoveryProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type PromoteRecoveryRequest struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Binding           *RecoveryBinding           `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	TransportEvidence *RecoveryTransportEvidence `protobuf:"bytes,2,opt,name=transport_evidence,json=transportEvidence,proto3" json:"transport_evidence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromoteRecoveryRequest) Reset() {
	*x = PromoteRecoveryRequest{}
	mi := &file_trading_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRecoveryRequest) ProtoMessage() {}

func (x *PromoteRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRecoveryRequest.ProtoReflect.Descriptor instead.
func (*PromoteRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{15}
}

func (x *PromoteRecoveryRequest) GetBinding() *RecoveryBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *PromoteRecoveryRequest) GetTransportEvidence() *RecoveryTransportEvidence {
	if x != nil {
		return x.TransportEvidence
	}
	return nil
}

type RecoveryStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MarketId            string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	EpochId             string                 `protobuf:"bytes,2,opt,name=epoch_id,json=epochId,proto3" json:"epoch_id,omitempty"`
	Phase               string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Version             string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	RuntimeSequence     string                 `protobuf:"bytes,5,opt,name=runtime_sequence,json=runtimeSequence,proto3" json:"runtime_sequence,omitempty"`
	StateHash           string                 `protobuf:"bytes,6,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	WritesEnabled       bool                   `protobuf:"varint,7,opt,name=writes_enabled,json=writesEnabled,proto3" json:"writes_enabled,omitempty"`
	ContinuityUncertain bool                   `protobuf:"varint,8,opt,name=continuity_uncertain,json=continuityUncertain,proto3" json:"continuity_uncertain,omitempty"`
	ContinuityError     string                 `protobuf:"bytes,9,opt,name=continuity_error,json=continuityError,proto3" json:"continuity_error,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Provenance          *RecoveryProvenance    `protobuf:"bytes,11,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecoveryStatusResponse) Reset() {
	*x = RecoveryStatusResponse{}
	mi := &file_trading_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryStatusResponse) ProtoMessage() {}

func (x *RecoveryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryStatusResponse.ProtoReflect.Descriptor instead.
func (*RecoveryStatusResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{16}
}

func (x *RecoveryStatusResponse) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *RecoveryStatusResponse) GetEpochId() string {
	if x != nil {
		return x.EpochId
	}
	return ""
}

func (x *RecoveryStatusResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RecoveryStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RecoveryStatusResponse) GetRuntimeSequence() string {
	if x != nil {
		return x.RuntimeSequence
	}
	return ""
}

func (x *RecoveryStatusResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *RecoveryStatusResponse) GetWritesEnabled() bool {
	if x != nil {
		return x.WritesEnabled
	}
	return false
}

func (x *RecoveryStatusResponse) GetContinuityUncertain() bool {
	if x != nil {
		return x.ContinuityUncertain
	}
	return false
}

func (x *RecoveryStatusResponse) GetContinuityError() string {
	if x != nil {
		return x.ContinuityError
	}
	return ""
}

func (x *RecoveryStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RecoveryStatusResponse) GetProvenance() *RecoveryProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type AdminFundVirtualRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFundVirtualRequest) Reset() {
	*x = AdminFundVirtualRequest{}
	mi := &file_trading_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFundVirtualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFundVirtualRequest) ProtoMessage() {}

func (x *AdminFundVirtualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFundVirtualRequest.ProtoReflect.Descriptor instead.
func (*AdminFundVirtualRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{17}
}

func (x *AdminFundVirtualRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *AdminFundVirtualRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AdminFundVirtualRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AdminFundVirtualRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *AdminFundVirtualRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SubscribeEventsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MarketId         string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	CursorSequence   string                 `protobuf:"bytes,2,opt,name=cursor_sequence,json=cursorSequence,proto3" json:"cursor_sequence,omitempty"`
	CursorEventIndex uint32                 `protobuf:"varint,3,opt,name=cursor_event_index,json=cursorEventIndex,proto3" json:"cursor_event_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_trading_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeEventsRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *SubscribeEventsRequest) GetCursorSequence() string {
	if x != nil {
		return x.CursorSequence
	}
	return ""
}

func (x *SubscribeEventsRequest) GetCursorEventIndex() uint32 {
	if x != nil {
		return x.CursorEventIndex
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      string                 `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Events        []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_trading_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{19}
}

func (x *CommandResult) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *CommandResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Order struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientOrderId        string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	AccountId            string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MarketId             string                 `protobuf:"bytes,4,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side                 string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Type                 string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	TimeInForce          string                 `protobuf:"bytes,7,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	PostOnly             bool                   `protobuf:"varint,8,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	Price                string                 `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	OriginalQuantity     string                 `protobuf:"bytes,10,opt,name=original_quantity,json=originalQuantity,proto3" json:"original_quantity,omitempty"`
	RemainingQuantity    string                 `protobuf:"bytes,11,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	FilledQuantity       string                 `protobuf:"bytes,12,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	OriginalQuoteBudget  string                 `protobuf:"bytes,13,opt,name=original_quote_budget,json=originalQuoteBudget,proto3" json:"original_quote_budget,omitempty"`
	RemainingQuoteBudget string                 `protobuf:"bytes,14,opt,name=remaining_quote_budget,json=remainingQuoteBudget,proto3" json:"remaining_quote_budget,omitempty"`
	SpentQuote           string                 `protobuf:"bytes,15,opt,name=spent_quote,json=spentQuote,proto3" json:"spent_quote,omitempty"`
	HeldAsset            string                 `protobuf:"bytes,16,opt,name=held_asset,json=heldAsset,proto3" json:"held_asset,omitempty"`
	HeldAmount           string                 `protobuf:"bytes,17,opt,name=held_amount,json=heldAmount,proto3" json:"held_amount,omitempty"`
	Status               string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	AcceptedSequence     string                 `protobuf:"bytes,19,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	LastSequence         string                 `protobuf:"bytes,20,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	RejectReason         string                 `protobuf:"bytes,21,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_trading_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{20}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Order) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Order) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Order) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Order) GetTimeInForce() string {
	if x != nil {
		return x.TimeInForce
	}
	return ""
}

func (x *Order) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetOriginalQuantity() string {
	if x != nil {
		return x.OriginalQuantity
	}
	return ""
}

func (x *Order) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

func (x *Order) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *Order) GetOriginalQuoteBudget() string {
	if x != nil {
		return x.OriginalQuoteBudget
	}
	return ""
}

func (x *Order) GetRemainingQuoteBudget() string {
	if x != nil {
		return x.RemainingQuoteBudget
	}
	return ""
}

func (x *Order) GetSpentQuote() string {
	if x != nil {
		return x.SpentQuote
	}
	return ""
}

func (x *Order) GetHeldAsset() string {
	if x != nil {
		return x.HeldAsset
	}
	return ""
}

func (x *Order) GetHeldAmount() string {
	if x != nil {
		return x.HeldAmount
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetAcceptedSequence() string {
	if x != nil {
		return x.AcceptedSequence
	}
	return ""
}

func (x *Order) GetLastSequence() string {
	if x != nil {
		return x.LastSequence
	}
	return ""
}

func (x *Order) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	RateBps       string                 `protobuf:"bytes,4,opt,name=rate_bps,json=rateBps,proto3" json:"rate_bps,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_trading_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{21}
}

func (x *Fee) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Fee) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Fee) GetRateBps() string {
	if x != nil {
		return x.RateBps
	}
	return ""
}

func (x *Fee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Trade struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId        string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Price           string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity        string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuoteAmount     string                 `protobuf:"bytes,5,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	MakerOrderId    string                 `protobuf:"bytes,6,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId    string                 `protobuf:"bytes,7,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerAccountId  string                 `protobuf:"bytes,8,opt,name=maker_account_id,json=makerAccountId,proto3" json:"maker_account_id,omitempty"`
	TakerAccountId  string                 `protobuf:"bytes,9,opt,name=taker_account_id,json=takerAccountId,proto3" json:"taker_account_id,omitempty"`
	BuyerAccountId  string                 `protobuf:"bytes,10,opt,name=buyer_account_id,json=buyerAccountId,proto3" json:"buyer_account_id,omitempty"`
	SellerAccountId string                 `protobuf:"bytes,11,opt,name=seller_account_id,json=sellerAccountId,proto3" json:"seller_account_id,omitempty"`
	BuyerFee        *Fee                   `protobuf:"bytes,12,opt,name=buyer_fee,json=buyerFee,proto3" json:"buyer_fee,omitempty"`
	SellerFee       *Fee                   `protobuf:"bytes,13,opt,name=seller_fee,json=sellerFee,proto3" json:"seller_fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_trading_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{22}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *Trade) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *Trade) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *Trade) GetMakerAccountId() string {
	if x != nil {
		return x.MakerAccountId
	}
	return ""
}

func (x *Trade) GetTakerAccountId() string {
	if x != nil {
		return x.TakerAccountId
	}
	return ""
}

func (x *Trade) GetBuyerAccountId() string {
	if x != nil {
		return x.BuyerAccountId
	}
	return ""
}

func (x *Trade) GetSellerAccountId() string {
	if x != nil {
		return x.SellerAccountId
	}
	return ""
}

func (x *Trade) GetBuyerFee() *Fee {
	if x != nil {
		return x.BuyerFee
	}
	return nil
}

func (x *Trade) GetSellerFee() *Fee {
	if x != nil {
		return x.SellerFee
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      string                 `protobuf:"bytes,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,6,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Side          string                 `protobuf:"bytes,8,opt,name=side,proto3" json:"side,omitempty"`
	Price         string                 `protobuf:"bytes,9,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,10,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remaining     string                 `protobuf:"bytes,11,opt,name=remaining,proto3" json:"remaining,omitempty"`
	QuoteAmount   string                 `protobuf:"bytes,12,opt,name=quote_amount,json=quoteAmount,proto3" json:"quote_amount,omitempty"`
	Asset         string                 `protobuf:"bytes,13,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,14,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,15,opt,name=reason,proto3" json:"reason,omitempty"`
	Trade         *Trade                 `protobuf:"bytes,16,opt,name=trade,proto3" json:"trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_trading_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{23}
}

func (x *Event) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *Event) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Event) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Event) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Event) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Event) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Event) GetRemaining() string {
	if x != nil {
		return x.Remaining
	}
	return ""
}

func (x *Event) GetQuoteAmount() string {
	if x != nil {
		return x.QuoteAmount
	}
	return ""
}

func (x *Event) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Event) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Event) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Event) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Available     string                 `protobuf:"bytes,2,opt,name=available,proto3" json:"available,omitempty"`
	Held          string                 `protobuf:"bytes,3,opt,name=held,proto3" json:"held,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_trading_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{24}
}

func (x *Balance) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Balance) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *Balance) GetHeld() string {
	if x != nil {
		return x.Held
	}
	return ""
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount    uint32                 `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_trading_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{25}
}

func (x *PriceLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PriceLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PriceLevel) GetOrderCount() uint32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

type OrderBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Sequence      string                 `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Bids          []*PriceLevel          `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*PriceLevel          `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	mi := &file_trading_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{26}
}

func (x *OrderBook) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *OrderBook) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *OrderBook) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBook) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type StatusResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	MarketId                   string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	State                      string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Sequence                   string                 `protobuf:"bytes,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	QueueDepth                 uint32                 `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	RecoveryCount              string                 `protobuf:"bytes,5,opt,name=recovery_count,json=recoveryCount,proto3" json:"recovery_count,omitempty"`
	LastError                  string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastIncident               string                 `protobuf:"bytes,7,opt,name=last_incident,json=lastIncident,proto3" json:"last_incident,omitempty"`
	LastIncidentAt             string                 `protobuf:"bytes,8,opt,name=last_incident_at,json=lastIncidentAt,proto3" json:"last_incident_at,omitempty"`
	LastRecoveredAt            string                 `protobuf:"bytes,9,opt,name=last_recovered_at,json=lastRecoveredAt,proto3" json:"last_recovered_at,omitempty"`
	OutboxState                string                 `protobuf:"bytes,10,opt,name=outbox_state,json=outboxState,proto3" json:"outbox_state,omitempty"`
	OutboxCheckpointSequence   string                 `protobuf:"bytes,11,opt,name=outbox_checkpoint_sequence,json=outboxCheckpointSequence,proto3" json:"outbox_checkpoint_sequence,omitempty"`
	OutboxCheckpointEventIndex uint32                 `protobuf:"varint,12,opt,name=outbox_checkpoint_event_index,json=outboxCheckpointEventIndex,proto3" json:"outbox_checkpoint_event_index,omitempty"`
	OutboxLastError            string                 `protobuf:"bytes,13,opt,name=outbox_last_error,json=outboxLastError,proto3" json:"outbox_last_error,omitempty"`
	OutboxLastPublishedAt      string                 `protobuf:"bytes,14,opt,name=outbox_last_published_at,json=outboxLastPublishedAt,proto3" json:"outbox_last_published_at,omitempty"`
	OutboxLastCleanupAt        string                 `protobuf:"bytes,15,opt,name=outbox_last_cleanup_at,json=outboxLastCleanupAt,proto3" json:"outbox_last_cleanup_at,omitempty"`
	StateHash                  string                 `protobuf:"bytes,16,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_trading_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{27}
}

func (x *StatusResponse) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *StatusResponse) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *StatusResponse) GetRecoveryCount() string {
	if x != nil {
		return x.RecoveryCount
	}
	return ""
}

func (x *StatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *StatusResponse) GetLastIncident() string {
	if x != nil {
		return x.LastIncident
	}
	return ""
}

func (x *StatusResponse) GetLastIncidentAt() string {
	if x != nil {
		return x.LastIncidentAt
	}
	return ""
}

func (x *StatusResponse) GetLastRecoveredAt() string {
	if x != nil {
		return x.LastRecoveredAt
	}
	return ""
}

func (x *StatusResponse) GetOutboxState() string {
	if x != nil {
		return x.OutboxState
	}
	return ""
}

func (x *StatusResponse) GetOutboxCheckpointSequence() string {
	if x != nil {
		return x.OutboxCheckpointSequence
	}
	return ""
}

func (x *StatusResponse) GetOutboxCheckpointEventIndex() uint32 {
	if x != nil {
		return x.OutboxCheckpointEventIndex
	}
	return 0
}

func (x *StatusResponse) GetOutboxLastError() string {
	if x != nil {
		return x.OutboxLastError
	}
	return ""
}

func (x *StatusResponse) GetOutboxLastPublishedAt() string {
	if x != nil {
		return x.OutboxLastPublishedAt
	}
	return ""
}

func (x *StatusResponse) GetOutboxLastCleanupAt() string {
	if x != nil {
		return x.OutboxLastCleanupAt
	}
	return ""
}

func (x *StatusResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Sequence      string                 `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	EventIndex    uint32                 `protobuf:"varint,3,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	Event         *Event                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_trading_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_trading_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_trading_proto_rawDescGZIP(), []int{28}
}

func (x *EventEnvelope) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventEnvelope) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *EventEnvelope) GetEventIndex() uint32 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *EventEnvelope) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_trading_proto protoreflect.FileDescriptor

const file_trading_proto_rawDesc = "" +
	"\n" +
	"\rtrading.proto\x12\x0es78.trading.v1\"\x84\x03\n" +
	"\x12SubmitOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\tR\rclientOrderId\x12(\n" +
	"\x04side\x18\x04 \x01(\x0e2\x14.s78.trading.v1.SideR\x04side\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.s78.trading.v1.OrderTypeR\x04type\x12?\n" +
	"\rtime_in_force\x18\x06 \x01(\x0e2\x1b.s78.trading.v1.TimeInForceR\vtimeInForce\x12\x1b\n" +
	"\tpost_only\x18\a \x01(\bR\bpostOnly\x12\x14\n" +
	"\x05price\x18\b \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\t \x01(\tR\bquantity\x12!\n" +
	"\fquote_budget\x18\n" +
	" \x01(\tR\vquoteBudget\"\x8a\x01\n" +
	"\x12CancelOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\"h\n" +
	"\x0fGetOrderRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\x82\x01\n" +
	"\x11ListOrdersRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\topen_only\x18\x03 \x01(\bR\bopenOnly\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"C\n" +
	"\x12ListOrdersResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.s78.trading.v1.OrderR\x06orders\"e\n" +
	"\x11ListTradesRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"C\n" +
	"\x12ListTradesResponse\x12-\n" +
	"\x06trades\x18\x01 \x03(\v2\x15.s78.trading.v1.TradeR\x06trades\"P\n" +
	"\x12GetBalancesRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"J\n" +
	"\x13GetBalancesResponse\x123\n" +
	"\bbalances\x18\x01 \x03(\v2\x17.s78.trading.v1.BalanceR\bbalances\"J\n" +
	"\x13GetOrderBookRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06levels\x18\x02 \x01(\rR\x06levels\"/\n" +
	"\x10GetStatusRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"7\n" +
	"\x18GetRecoveryStatusRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"\xf1\x01\n" +
	"\x0fRecoveryBinding\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\tR\aepochId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12)\n" +
	"\x10runtime_sequence\x18\x04 \x01(\tR\x0fruntimeSequence\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x05 \x01(\tR\tstateHash\x12B\n" +
	"\n" +
	"provenance\x18\x06 \x01(\v2\".s78.trading.v1.RecoveryProvenanceR\n" +
	"provenance\"\xd9\x01\n" +
	"\x12RecoveryProvenance\x12+\n" +
	"\x11production_origin\x18\x01 \x01(\tR\x10productionOrigin\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12%\n" +
	"\x0erelease_commit\x18\x03 \x01(\tR\rreleaseCommit\x12#\n" +
	"\rsource_digest\x18\x04 \x01(\tR\fsourceDigest\x12%\n" +
	"\x0edeployment_url\x18\x05 \x01(\tR\rdeploymentUrl\"\x9f\x02\n" +
	"\x19RecoveryTransportEvidence\x12!\n" +
	"\fsample_count\x18\x01 \x01(\rR\vsampleCount\x12&\n" +
	"\x0ffirst_sample_at\x18\x02 \x01(\tR\rfirstSampleAt\x12$\n" +
	"\x0elast_sample_at\x18\x03 \x01(\tR\flastSampleAt\x12$\n" +
	"\x0emaximum_gap_ms\x18\x04 \x01(\tR\fmaximumGapMs\x12'\n" +
	"\x0fevidence_sha256\x18\x05 \x01(\tR\x0eevidenceSha256\x12B\n" +
	"\n" +
	"provenance\x18\x06 \x01(\v2\".s78.trading.v1.RecoveryProvenanceR\n" +
	"provenance\"\xad\x01\n" +
	"\x16PromoteRecoveryRequest\x129\n" +
	"\abinding\x18\x01 \x01(\v2\x1f.s78.trading.v1.RecoveryBindingR\abinding\x12X\n" +
	"\x12transport_evidence\x18\x02 \x01(\v2).s78.trading.v1.RecoveryTransportEvidenceR\x11transportEvidence\"\xb2\x03\n" +
	"\x16RecoveryStatusResponse\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bepoch_id\x18\x02 \x01(\tR\aepochId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12)\n" +
	"\x10runtime_sequence\x18\x05 \x01(\tR\x0fruntimeSequence\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x06 \x01(\tR\tstateHash\x12%\n" +
	"\x0ewrites_enabled\x18\a \x01(\bR\rwritesEnabled\x121\n" +
	"\x14continuity_uncertain\x18\b \x01(\bR\x13continuityUncertain\x12)\n" +
	"\x10continuity_error\x18\t \x01(\tR\x0fcontinuityError\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12B\n" +
	"\n" +
	"provenance\x18\v \x01(\v2\".s78.trading.v1.RecoveryProvenanceR\n" +
	"provenance\"\xa2\x01\n" +
	"\x17AdminFundVirtualRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\x8c\x01\n" +
	"\x16SubscribeEventsRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12'\n" +
	"\x0fcursor_sequence\x18\x02 \x01(\tR\x0ecursorSequence\x12,\n" +
	"\x12cursor_event_index\x18\x03 \x01(\rR\x10cursorEventIndex\"\x8d\x01\n" +
	"\rCommandResult\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\tR\bsequence\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x06events\x18\x04 \x03(\v2\x15.s78.trading.v1.EventR\x06events\"\xd9\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x1b\n" +
	"\tmarket_id\x18\x04 \x01(\tR\bmarketId\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\"\n" +
	"\rtime_in_force\x18\a \x01(\tR\vtimeInForce\x12\x1b\n" +
	"\tpost_only\x18\b \x01(\bR\bpostOnly\x12\x14\n" +
	"\x05price\x18\t \x01(\tR\x05price\x12+\n" +
	"\x11original_quantity\x18\n" +
	" \x01(\tR\x10originalQuantity\x12-\n" +
	"\x12remaining_quantity\x18\v \x01(\tR\x11remainingQuantity\x12'\n" +
	"\x0ffilled_quantity\x18\f \x01(\tR\x0efilledQuantity\x122\n" +
	"\x15original_quote_budget\x18\r \x01(\tR\x13originalQuoteBudget\x124\n" +
	"\x16remaining_quote_budget\x18\x0e \x01(\tR\x14remainingQuoteBudget\x12\x1f\n" +
	"\vspent_quote\x18\x0f \x01(\tR\n" +
	"spentQuote\x12\x1d\n" +
	"\n" +
	"held_asset\x18\x10 \x01(\tR\theldAsset\x12\x1f\n" +
	"\vheld_amount\x18\x11 \x01(\tR\n" +
	"heldAmount\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\x12+\n" +
	"\x11accepted_sequence\x18\x13 \x01(\tR\x10acceptedSequence\x12#\n" +
	"\rlast_sequence\x18\x14 \x01(\tR\flastSequence\x12#\n" +
	"\rreject_reason\x18\x15 \x01(\tR\frejectReason\"\x81\x01\n" +
	"\x03Fee\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x19\n" +
	"\brate_bps\x18\x04 \x01(\tR\arateBps\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\xe5\x03\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12!\n" +
	"\fquote_amount\x18\x05 \x01(\tR\vquoteAmount\x12$\n" +
	"\x0emaker_order_id\x18\x06 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\a \x01(\tR\ftakerOrderId\x12(\n" +
	"\x10maker_account_id\x18\b \x01(\tR\x0emakerAccountId\x12(\n" +
	"\x10taker_account_id\x18\t \x01(\tR\x0etakerAccountId\x12(\n" +
	"\x10buyer_account_id\x18\n" +
	" \x01(\tR\x0ebuyerAccountId\x12*\n" +
	"\x11seller_account_id\x18\v \x01(\tR\x0fsellerAccountId\x120\n" +
	"\tbuyer_fee\x18\f \x01(\v2\x13.s78.trading.v1.FeeR\bbuyerFee\x122\n" +
	"\n" +
	"seller_fee\x18\r \x01(\v2\x13.s78.trading.v1.FeeR\tsellerFee\"\xc1\x03\n" +
	"\x05Event\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\tR\bsequence\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x06 \x01(\tR\rclientOrderId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x12\n" +
	"\x04side\x18\b \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\t \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\n" +
	" \x01(\tR\bquantity\x12\x1c\n" +
	"\tremaining\x18\v \x01(\tR\tremaining\x12!\n" +
	"\fquote_amount\x18\f \x01(\tR\vquoteAmount\x12\x14\n" +
	"\x05asset\x18\r \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x0e \x01(\tR\x06amount\x12\x16\n" +
	"\x06reason\x18\x0f \x01(\tR\x06reason\x12+\n" +
	"\x05trade\x18\x10 \x01(\v2\x15.s78.trading.v1.TradeR\x05trade\"Q\n" +
	"\aBalance\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\tR\tavailable\x12\x12\n" +
	"\x04held\x18\x03 \x01(\tR\x04held\"_\n" +
	"\n" +
	"PriceLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\rR\n" +
	"orderCount\"\xa4\x01\n" +
	"\tOrderBook\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\tR\bsequence\x12.\n" +
	"\x04bids\x18\x03 \x03(\v2\x1a.s78.trading.v1.PriceLevelR\x04bids\x12.\n" +
	"\x04asks\x18\x04 \x03(\v2\x1a.s78.trading.v1.PriceLevelR\x04asks\"\x9e\x05\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\tR\bsequence\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\rR\n" +
	"queueDepth\x12%\n" +
	"\x0erecovery_count\x18\x05 \x01(\tR\rrecoveryCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12#\n" +
	"\rlast_incident\x18\a \x01(\tR\flastIncident\x12(\n" +
	"\x10last_incident_at\x18\b \x01(\tR\x0elastIncidentAt\x12*\n" +
	"\x11last_recovered_at\x18\t \x01(\tR\x0flastRecoveredAt\x12!\n" +
	"\foutbox_state\x18\n" +
	" \x01(\tR\voutboxState\x12<\n" +
	"\x1aoutbox_checkpoint_sequence\x18\v \x01(\tR\x18outboxCheckpointSequence\x12A\n" +
	"\x1doutbox_checkpoint_event_index\x18\f \x01(\rR\x1aoutboxCheckpointEventIndex\x12*\n" +
	"\x11outbox_last_error\x18\r \x01(\tR\x0foutboxLastError\x127\n" +
	"\x18outbox_last_published_at\x18\x0e \x01(\tR\x15outboxLastPublishedAt\x123\n" +
	"\x16outbox_last_cleanup_at\x18\x0f \x01(\tR\x13outboxLastCleanupAt\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x10 \x01(\tR\tstateHash\"\x96\x01\n" +
	"\rEventEnvelope\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\tR\bsequence\x12\x1f\n" +
	"\vevent_index\x18\x03 \x01(\rR\n" +
	"eventIndex\x12+\n" +
	"\x05event\x18\x04 \x01(\v2\x15.s78.trading.v1.EventR\x05event*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*q\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x032\x9b\b\n" +
	"\x0eTradingService\x12P\n" +
	"\vSubmitOrder\x12\".s78.trading.v1.SubmitOrderRequest\x1a\x1d.s78.trading.v1.CommandResult\x12P\n" +
	"\vCancelOrder\x12\".s78.trading.v1.CancelOrderRequest\x1a\x1d.s78.trading.v1.CommandResult\x12B\n" +
	"\bGetOrder\x12\x1f.s78.trading.v1.GetOrderRequest\x1a\x15.s78.trading.v1.Order\x12S\n" +
	"\n" +
	"ListOrders\x12!.s78.trading.v1.ListOrdersRequest\x1a\".s78.trading.v1.ListOrdersResponse\x12S\n" +
	"\n" +
	"ListTrades\x12!.s78.trading.v1.ListTradesRequest\x1a\".s78.trading.v1.ListTradesResponse\x12V\n" +
	"\vGetBalances\x12\".s78.trading.v1.GetBalancesRequest\x1a#.s78.trading.v1.GetBalancesResponse\x12N\n" +
	"\fGetOrderBook\x12#.s78.trading.v1.GetOrderBookRequest\x1a\x19.s78.trading.v1.OrderBook\x12M\n" +
	"\tGetStatus\x12 .s78.trading.v1.GetStatusRequest\x1a\x1e.s78.trading.v1.StatusResponse\x12e\n" +
	"\x11GetRecoveryStatus\x12(.s78.trading.v1.GetRecoveryStatusRequest\x1a&.s78.trading.v1.RecoveryStatusResponse\x12a\n" +
	"\x0fPromoteRecovery\x12&.s78.trading.v1.PromoteRecoveryRequest\x1a&.s78.trading.v1.RecoveryStatusResponse\x12Z\n" +
	"\x10AdminFundVirtual\x12'.s78.trading.v1.AdminFundVirtualRequest\x1a\x1d.s78.trading.v1.CommandResult\x12Z\n" +
	"\x0fSubscribeEvents\x12&.s78.trading.v1.SubscribeEventsRequest\x1a\x1d.s78.trading.v1.EventEnvelope0\x01BBZ@github.com/the-web3/s78-market-services/trading/rpc/pb;tradingv1b\x06proto3"

var (
	file_trading_proto_rawDescOnce sync.Once
	file_trading_proto_rawDescData []byte
)

func file_trading_proto_rawDescGZIP() []byte {
	file_trading_proto_rawDescOnce.Do(func() {
		file_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_proto_rawDesc), len(file_trading_proto_rawDesc)))
	})
	return file_trading_proto_rawDescData
}

var file_trading_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_trading_proto_goTypes = []any{
	(Side)(0),                         // 0: s78.trading.v1.Side
	(OrderType)(0),                    // 1: s78.trading.v1.OrderType
	(TimeInForce)(0),                  // 2: s78.trading.v1.TimeInForce
	(*SubmitOrderRequest)(nil),        // 3: s78.trading.v1.SubmitOrderRequest
	(*CancelOrderRequest)(nil),        // 4: s78.trading.v1.CancelOrderRequest
	(*GetOrderRequest)(nil),           // 5: s78.trading.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),         // 6: s78.trading.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 7: s78.trading.v1.ListOrdersResponse
	(*ListTradesRequest)(nil),         // 8: s78.trading.v1.ListTradesRequest
	(*ListTradesResponse)(nil),        // 9: s78.trading.v1.ListTradesResponse
	(*GetBalancesRequest)(nil),        // 10: s78.trading.v1.GetBalancesRequest
	(*GetBalancesResponse)(nil),       // 11: s78.trading.v1.GetBalancesResponse
	(*GetOrderBookRequest)(nil),       // 12: s78.trading.v1.GetOrderBookRequest
	(*GetStatusRequest)(nil),          // 13: s78.trading.v1.GetStatusRequest
	(*GetRecoveryStatusRequest)(nil),  // 14: s78.trading.v1.GetRecoveryStatusRequest
	(*RecoveryBinding)(nil),           // 15: s78.trading.v1.RecoveryBinding
	(*RecoveryProvenance)(nil),        // 16: s78.trading.v1.RecoveryProvenance
	(*RecoveryTransportEvidence)(nil), // 17: s78.trading.v1.RecoveryTransportEvidence
	(*PromoteRecoveryRequest)(nil),    // 18: s78.trading.v1.PromoteRecoveryRequest
	(*RecoveryStatusResponse)(nil),    // 19: s78.trading.v1.RecoveryStatusResponse
	(*AdminFundVirtualRequest)(nil),   // 20: s78.trading.v1.AdminFundVirtualRequest
	(*SubscribeEventsRequest)(nil),    // 21: s78.trading.v1.SubscribeEventsRequest
	(*CommandResult)(nil),             // 22: s78.trading.v1.CommandResult
	(*Order)(nil),                     // 23: s78.trading.v1.Order
	(*Fee)(nil),                       // 24: s78.trading.v1.Fee
	(*Trade)(nil),                     // 25: s78.trading.v1.Trade
	(*Event)(nil),                     // 26: s78.trading.v1.Event
	(*Balance)(nil),                   // 27: s78.trading.v1.Balance
	(*PriceLevel)(nil),                // 28: s78.trading.v1.PriceLevel
	(*OrderBook)(nil),                 // 29: s78.trading.v1.OrderBook
	(*StatusResponse)(nil),            // 30: s78.trading.v1.StatusResponse
	(*EventEnvelope)(nil),             // 31: s78.trading.v1.EventEnvelope
}
var file_trading_proto_depIdxs = []int32{
	0,  // 0: s78.trading.v1.SubmitOrderRequest.side:type_name -> s78.trading.v1.Side
	1,  // 1: s78.trading.v1.SubmitOrderRequest.type:type_name -> s78.trading.v1.OrderType
	2,  // 2: s78.trading.v1.SubmitOrderRequest.time_in_force:type_name -> s78.trading.v1.TimeInForce
	23, // 3: s78.trading.v1.ListOrdersResponse.orders:type_name -> s78.trading.v1.Order
	25, // 4: s78.trading.v1.ListTradesResponse.trades:type_name -> s78.trading.v1.Trade
	27, // 5: s78.trading.v1.GetBalancesResponse.balances:type_name -> s78.trading.v1.Balance
	16, // 6: s78.trading.v1.RecoveryBinding.provenance:type_name -> s78.trading.v1.RecoveryProvenance
	16, // 7: s78.trading.v1.RecoveryTransportEvidence.provenance:type_name -> s78.trading.v1.RecoveryProvenance
	15, // 8: s78.trading.v1.PromoteRecoveryRequest.binding:type_name -> s78.trading.v1.RecoveryBinding
	17, // 9: s78.trading.v1.PromoteRecoveryRequest.transport_evidence:type_name -> s78.trading.v1.RecoveryTransportEvidence
	16, // 10: s78.trading.v1.RecoveryStatusResponse.provenance:type_name -> s78.trading.v1.RecoveryProvenance
	26, // 11: s78.trading.v1.CommandResult.events:type_name -> s78.trading.v1.Event
	24, // 12: s78.trading.v1.Trade.buyer_fee:type_name -> s78.trading.v1.Fee
	24, // 13: s78.trading.v1.Trade.seller_fee:type_name -> s78.trading.v1.Fee
	25, // 14: s78.trading.v1.Event.trade:type_name -> s78.trading.v1.Trade
	28, // 15: s78.trading.v1.OrderBook.bids:type_name -> s78.trading.v1.PriceLevel
	28, // 16: s78.trading.v1.OrderBook.asks:type_name -> s78.trading.v1.PriceLevel
	26, // 17: s78.trading.v1.EventEnvelope.event:type_name -> s78.trading.v1.Event
	3,  // 18: s78.trading.v1.TradingService.SubmitOrder:input_type -> s78.trading.v1.SubmitOrderRequest
	4,  // 19: s78.trading.v1.TradingService.CancelOrder:input_type -> s78.trading.v1.CancelOrderRequest
	5,  // 20: s78.trading.v1.TradingService.GetOrder:input_type -> s78.trading.v1.GetOrderRequest
	6,  // 21: s78.trading.v1.TradingService.ListOrders:input_type -> s78.trading.v1.ListOrdersRequest
	8,  // 22: s78.trading.v1.TradingService.ListTrades:input_type -> s78.trading.v1.ListTradesRequest
	10, // 23: s78.trading.v1.TradingService.GetBalances:input_type -> s78.trading.v1.GetBalancesRequest
	12, // 24: s78.trading.v1.TradingService.GetOrderBook:input_type -> s78.trading.v1.GetOrderBookRequest
	13, // 25: s78.trading.v1.TradingService.GetStatus:input_type -> s78.trading.v1.GetStatusRequest
	14, // 26: s78.trading.v1.TradingService.GetRecoveryStatus:input_type -> s78.trading.v1.GetRecoveryStatusRequest
	18, // 27: s78.trading.v1.TradingService.PromoteRecovery:input_type -> s78.trading.v1.PromoteRecoveryRequest
	20, // 28: s78.trading.v1.TradingService.AdminFundVirtual:input_type -> s78.trading.v1.AdminFundVirtualRequest
	21, // 29: s78.trading.v1.TradingService.SubscribeEvents:input_type -> s78.trading.v1.SubscribeEventsRequest
	22, // 30: s78.trading.v1.TradingService.SubmitOrder:output_type -> s78.trading.v1.CommandResult
	22, // 31: s78.trading.v1.TradingService.CancelOrder:output_type -> s78.trading.v1.CommandResult
	23, // 32: s78.trading.v1.TradingService.GetOrder:output_type -> s78.trading.v1.Order
	7,  // 33: s78.trading.v1.TradingService.ListOrders:output_type -> s78.trading.v1.ListOrdersResponse
	9,  // 34: s78.trading.v1.TradingService.ListTrades:output_type -> s78.trading.v1.ListTradesResponse
	11, // 35: s78.trading.v1.TradingService.GetBalances:output_type -> s78.trading.v1.GetBalancesResponse
	29, // 36: s78.trading.v1.TradingService.GetOrderBook:output_type -> s78.trading.v1.OrderBook
	30, // 37: s78.trading.v1.TradingService.GetStatus:output_type -> s78.trading.v1.StatusResponse
	19, // 38: s78.trading.v1.TradingService.GetRecoveryStatus:output_type -> s78.trading.v1.RecoveryStatusResponse
	19, // 39: s78.trading.v1.TradingService.PromoteRecovery:output_type -> s78.trading.v1.RecoveryStatusResponse
	22, // 40: s78.trading.v1.TradingService.AdminFundVirtual:output_type -> s78.trading.v1.CommandResult
	31, // 41: s78.trading.v1.TradingService.SubscribeEvents:output_type -> s78.trading.v1.EventEnvelope
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_trading_proto_init() }
func file_trading_proto_init() {
	if File_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_proto_rawDesc), len(file_trading_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_proto_goTypes,
		DependencyIndexes: file_trading_proto_depIdxs,
		EnumInfos:         file_trading_proto_enumTypes,
		MessageInfos:      file_trading_proto_msgTypes,
	}.Build()
	File_trading_proto = out.File
	file_trading_proto_goTypes = nil
	file_trading_proto_depIdxs = nil
}
